#!/bin/bash
#PBS -N forest_dataset_download
#PBS -P pg06
#PBS -q copyq
#PBS -l ncpus=1
#PBS -l mem=8GB
#PBS -l walltime=2:00:00
#PBS -l storage=scratch/pg06
#PBS -l wd

module load python3/3.11.7

cd "$PBS_O_WORKDIR"

# run script for awscli
source .venv/bin/activate

root=/scratch/pg06/FYP2026S1_3473/forest_dataset
mkdir -p "$root"

echo "Starting download..."

export AWS_ACCESS_KEY_ID="KDC2ZFTBILDHXH843J8P"
export AWS_SECRET_ACCESS_KEY="z2HugVSyibm/uxqSfUE8um3P3NhqMFjLZXW/0YPL"


ENDPOINT_URL="https://s3.data.csiro.au"
SOURCE="s3://dapprd/000072329v001/"
DESTINATION="./72329v001"

aws s3 sync --endpoint-url "$ENDPOINT_URL" "$SOURCE" "$DESTINATION"

#for d in \
#    boreas-2024-12-04-14-34 \
#    boreas-2024-12-04-14-44 \
#    boreas-2024-12-23-17-01 \
#    boreas-2025-07-18-11-53 \
#    boreas-2024-12-04-14-38 \
#    boreas-2025-02-15-16-58; do

#     aws s3 sync "s3://boreas/$d" "$root/$d" \
#        --exclude "*" --include "camera/*" --no-sign-request
#done

echo "Download Completed"
