#!/bin/bash
#PBS -N forest_dataset_download
#PBS -P pg06
#PBS -q copyq
#PBS -l ncpus=1
#PBS -l mem=8GB
#PBS -l walltime=4:00:00
#PBS -l storage=scratch/pg06
#PBS -l wd


set -e  # Exit immediately if a command fails


module load python3/3.11.7

cd "$PBS_O_WORKDIR"

# run script for awscli
source .venv/bin/activate

root=/scratch/pg06/FYP2026S1_3473/forest_dataset
DESTINATION="$root/72329v001"
mkdir -p "$DESTINATION"

echo "Starting download..."

export AWS_ACCESS_KEY_ID="KDC2ZFTBILDHXH843J8P"
export AWS_SECRET_ACCESS_KEY="z2HugVSyibm/uxqSfUE8um3P3NhqMFjLZXW/0YPL"


ENDPOINT_URL="https://s3.data.csiro.au"
SOURCE="s3://dapprd/000072329v001/"

aws s3 sync --endpoint-url "$ENDPOINT_URL" "$SOURCE" "$DESTINATION"

#for d in \
#    boreas-2024-12-04-14-34 \
#    boreas-2024-12-04-14-44 \
#    boreas-2024-12-23-17-01 \
#    boreas-2025-07-18-11-53 \
#    boreas-2024-12-04-14-38 \
#    boreas-2025-02-15-16-58; do

#     aws s3 sync "s3://boreas/$d" "$root/$d" \
#        --exclude "*" --include "camera/*" --no-sign-request
#done

echo "Download Completed"


# cd "$DESTINATION"

# if [ -f "data/V-01/images_shrunk.tar.gz" ]; then
#     mkdir -p "data/V-01/shrunk_images"
#     tar -xzf "data/V-01/images_shrunk.tar.gz" -C "data/V-01/shrunk_images"
#     chmod -R +w "data/V-01/shrunk_images"
#     echo "Extracted V-01 images."
# fi

# echo "All tasks completed successfully."
