import json
import os
os.environ["HF_HOME"] = "/scratch/pg06/vm4618/huggingface_cache"
os.environ["HF_HUB_OFFLINE"] = "1"         # Force Hugging Face Hub offline
os.environ["TRANSFORMERS_OFFLINE"] = "1"   # Force Transformers offline
from decord import VideoReader, cpu
from PIL import Image
from vllm import LLM, SamplingParams

# Force Hugging Face cache to scratch to prevent crashing your NCI home quota
os.environ["HF_HOME"] = "/scratch/pg06/vm4618/huggingface_cache"

def format_timestamp(seconds):
    """Converts seconds into MM:SS format."""
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes:02d}:{secs:02d}"

def sample_frames_from_indices(vr, start_idx, end_idx, num_samples=16):
    """Uniformly samples 'num_samples' frames between start and end indices."""
    total_chunk_frames = end_idx - start_idx
    step = max(1, total_chunk_frames // num_samples)
    selected_indices = list(range(start_idx, end_idx, step))[:num_samples]
    
    batch = vr.get_batch(selected_indices).asnumpy()
    return [Image.fromarray(frame) for frame in batch]

def run_video_pipeline(
    video_path: str,
    full_history_json_path: str,
    change_analysis_json_path: str,
    vlm_model_name: str,
    frames_per_chunk: int = 300
):
    print("Loading modules...")
    # 1. Initialize Decord Video Reader
    vr = VideoReader(video_path, ctx=cpu(0))
    fps = vr.get_avg_fps()
    total_frames = len(vr)

    print(f"Loading VLM ({vlm_model_name}) into VRAM...")
    # 2. Initialize the single model for both Vision and Text tasks
    # Utilization bumped to 0.85 to give the model room on the 32GB GPU
    vlm = LLM(
        model=vlm_model_name, 
        enforce_eager=True, 
        dtype="half", 
        max_model_len=32768, 
        gpu_memory_utilization=0.85
    )

    vlm_params = SamplingParams(temperature=0.2, max_tokens=150)
    llm_params = SamplingParams(temperature=0.3, max_tokens=300)

    # Two distinct history buffers
    full_pipeline_history = []
    change_events_only = []
    
    previous_description = None
    chunk_idx = 0
    
    print("Starting video processing pipeline...")
    for start_frame in range(0, total_frames, frames_per_chunk):
        end_frame = min(start_frame + frames_per_chunk, total_frames)
        
        start_time_sec = start_frame / fps
        end_time_sec = end_frame / fps
        time_str = f"{format_timestamp(start_time_sec)} - {format_timestamp(end_time_sec)}"

        # Extract frames
        pil_frames = sample_frames_from_indices(vr, start_frame, end_frame, num_samples=16)

        # Step 1: Query VLM for scene description (Multi-Modal Prompt)
        vlm_prompt = "<|im_start|>user\n<|video_pad|>\nDescribe what is taking place in this scene in detail.<|im_end|>\n<|im_start|>assistant\n"
        vlm_output = vlm.generate(
            {"prompt": vlm_prompt, "multi_modal_data": {"video": pil_frames}},
            sampling_params=vlm_params
        )
        current_description = vlm_output[0].outputs[0].text.strip()

        # Step 2: Compare with Previous Scene using the SAME model (Text-Only Prompt)
        change_detected = False
        change_record = None

        if previous_description is not None:
            comparison_prompt = f"""<|im_start|>system
You are a video analysis assistant. Compare two consecutive video scene descriptions and identify if any NEW significant action, subject, or state change occurred. 
Don't compare the scences rather identify anything new found and structure the questions regarding a new event or object that appeared.
Create a question that can be answered without knowing the specifc scene and instead treat the scene as a chunk of a larger video and the question that can
be answered by looking at the video as a whole 
Return ONLY a valid JSON object matching this schema:
{{
  "something_new": true/false,
  "what_changed": "Description of change, or null if nothing changed",
  "question": "A question based on the new scene, or null if nothing changed",
  "answer": "The answer to the question based on the new scene, or null if nothing changed"
}}
<|im_end|>
<|im_start|>user
[PREVIOUS SCENE ({full_pipeline_history[-1]['timestamp']})]:
{previous_description}

[CURRENT SCENE ({time_str})]:
{current_description}
<|im_end|>
<|im_start|>assistant
"""
            # Generate purely using text via the same vlm object
            llm_output = vlm.generate(comparison_prompt, sampling_params=llm_params)
            comparison_raw = llm_output[0].outputs[0].text.strip()

            # Clean up potential markdown formatting generated by the model
            if comparison_raw.startswith("```json"):
                comparison_raw = comparison_raw.strip("`").replace("json\n", "", 1)

            try:
                parsed = json.loads(comparison_raw)
                change_detected = parsed.get("something_new", False)

                if change_detected:
                    change_record = {
                        "chunk_index": chunk_idx,
                        "timestamp": time_str,
                        "start_seconds": start_time_sec,
                        "what_changed": parsed.get("what_changed"),
                        "generated_qa": {
                            "question": parsed.get("question"),
                            "answer": parsed.get("answer")
                        },
                        "previous_scene": previous_description,
                        "current_scene": current_description
                    }
                    change_events_only.append(change_record)

            except json.JSONDecodeError:
                print(f"JSON error at chunk {chunk_idx}. Output was:\n[{comparison_raw}]")

        # Step 3: Build Full Log Entry
        log_entry = {
            "chunk_index": chunk_idx,
            "timestamp": time_str,
            "start_seconds": start_time_sec,
            "vlm_description": current_description,
            "change_detected": change_detected
        }
        full_pipeline_history.append(log_entry)

        # Step 4: Stream save both files to actual filenames
        with open(full_history_json_path, "w", encoding="utf-8") as f:
            json.dump(full_pipeline_history, f, indent=2)

        with open(change_analysis_json_path, "w", encoding="utf-8") as f:
            json.dump(change_events_only, f, indent=2)

        print(f"Chunk {chunk_idx} ({time_str}) processed | Change Detected: {change_detected}")
        
        previous_description = current_description
        chunk_idx += 1

    return full_pipeline_history, change_events_only

if __name__ == "__main__":
    # Fixed to ensure specific file outputs are generated rather than trying to overwrite directories
    video_path = "/scratch/pg06/vm4618/forrestDrive.mp4"
    run_video_pipeline(
        video_path=video_path,
        full_history_json_path=f"full_history-forrestDrive.json",
        change_analysis_json_path=f"change_analysisforrestDrive-forrestDrive.json",
        # Pass the DIRECT local path instead of the Hub repository name
        vlm_model_name="/scratch/pg06/vm4618/huggingface_cache/hub/models--Qwen--Qwen2-VL-7B-Instruct/snapshots/eed13092ef92e448dd6875b2a00151bd3f7db0ac"
    )