#!/bin/bash
#PBS -N sparse_event
#PBS -P pg06
#PBS -q gpuhopper
#PBS -l ncpus=24
#PBS -l ngpus=4
#PBS -l mem=512GB
#PBS -l walltime=05:00:00
#PBS -l storage=scratch/pg06
#PBS -l wd

module load python3/3.11.7
module load cuda/12.2.2

# cd to the right directory
cd "$PBS_O_WORKDIR"

# enter virutal environment for dependencies
source /scratch/pg06/vm4618/envs/vllm_env/bin/activate

# run main script
python3 main.py --mode sparse
