#!/bin/bash
#PBS -N sparse_event
#PBS -P pg06
#PBS -q gpuhopper
#PBS -l ncpus=12
#PBS -l ngpus=1
#PBS -l mem=64GB
#PBS -l walltime=01:00:00
#PBS -l jobfs=50GB
#PBS -l storage=scratch/pg06
#PBS -l wd

set -euo pipefail

module load python3/3.11.7
module load cuda/12.2.2

source /scratch/pg06/vm4618/envs/vllm_env/bin/activate

cd "$PBS_O_WORKDIR"
export PYTHONUNBUFFERED=1
export HF_HOME=/scratch/pg06/vm4618/huggingface_cache
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1

python3 main.py --mode sparse
