#!/bin/bash
#PBS -N temporal_event
#PBS -P pg06
#PBS -q gpuhopper
#PBS -l ncpus=48
#PBS -l ngpus=4
#PBS -l mem=1024GB
#PBS -l walltime=00:50:00
#PBS -l storage=scratch/pg06
#PBS -l wd
#PBS -V

module load python3/3.11.7

# cd to the right directory
cd "$PBS_O_WORKDIR"

# Enter the environment containing the OpenAI client and pipeline dependencies.
source /scratch/pg06/vm4618/envs/vllm_env/bin/activate

# run main script
python3 main.py --mode temporal
